---

name: "monitoring"

services:
  server:
    container_name: "monitoring-server"
    image: "akeb/monitoring-server:local"
    restart: unless-stopped
    build: .
    env_file:
      - ./.env
    volumes:
      # - ./src:/app
      - ./logs/php/:/var/log/php/:rw
      - ./logs/nginx/:/var/log/nginx/:rw
    ports:
      - "${NGINX_PORT}:80"
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
    depends_on:
      mysql:
          condition: service_healthy

  mysql:
    container_name: monitoring-mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
      - ${EXTERNAL_MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "${MYSQL_USERNAME}", "--password=${MYSQL_PASSWORD}"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55